-- ═══════════════════════════════════════════════════════════════════════
-- ASCOFIZZ — BASE SCHEMA
--
-- RUN THIS FIRST, on a brand-new Supabase project, before every other
-- migration in this directory.
--
-- WHY THIS FILE EXISTS
--   The platform this was forked from never had one. Its core tables —
--   orders, customers, products, coupons, refunds, reviews, settings and
--   the rest — were created by hand in the Supabase dashboard over time
--   and only ever existed in that one live project. Every migration in
--   this directory from 001 onward assumes they are already there;
--   db-selfcheck.js calls them "base schema" and has no file to point at.
--   That made the database impossible to stand up from source.
--
--   This file is that missing baseline. It was reconstructed from the
--   application code rather than from a dump, by reading every column the
--   server actually writes and reads:
--     • orders          — the ORDER_COLUMNS whitelist in server.js
--     • products        — the safeFields/arrayFields list in POST
--                         /api/admin/products, plus FRONTEND_OWNED_FIELDS
--     • coupons         — buildCouponPayload() and the validate path
--     • customers       — the insert/update in the order-placement path
--     • everything else — its insert() call sites
--
--   Where the old database's exact type or nullability could not be
--   recovered from code, the choice here is the permissive one, so this
--   never rejects a write the application makes. Constraints that the
--   code clearly relies on (unique coupon codes, unique customer email,
--   the order-id primary key) ARE enforced.
--
-- IDEMPOTENT
--   Every statement is `if not exists` / `or replace`. Safe to re-run.
--
-- ORDER OF EXECUTION
--   000_base_schema.sql   ← this file
--   002_atomic_counters.sql, 003_returns.sql, 004_…, 006_…, 007_…
--   …then the numbered hardening migrations
--   005_rls_lockdown.sql  ← last, after the app is confirmed working
--
--   See MIGRATIONS.md for the full ordered list.
-- ═══════════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ─────────────────────────────────────────────────────────────────────
-- PRODUCTS
--   id is bigint: decrement_stock(p_id bigint) in 002 depends on it.
--   Money is numeric(10,2) throughout — never float, which cannot
--   represent ₹0.05 exactly and drifts once totals are summed.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.products (
  id               bigint generated by default as identity primary key,
  name             text        not null,
  brand            text,
  category         text,
  badge            text,
  description      text,
  how_to_use       text,

  price            numeric(10,2) not null default 0,
  mrp              numeric(10,2),
  sale_price       numeric(10,2),
  cost_price       numeric(10,2),
  offer_text       text,
  has_tiers        boolean     not null default false,
  tiers            jsonb       not null default '[]'::jsonb,

  stock            integer     not null default 0,
  hsn              text,

  rating           numeric(3,2) default 0,
  reviews          integer      default 0,

  -- The storefront reads image..image5; the admin Photo Library writes
  -- them. `images`/`media` hold richer galleries for newer cards.
  image            text,
  image2           text,
  image3           text,
  image4           text,
  image5           text,
  images           jsonb       not null default '[]'::jsonb,
  media            jsonb       not null default '[]'::jsonb,

  tags             jsonb       not null default '[]'::jsonb,
  key_ingredients  jsonb       not null default '[]'::jsonb,
  seo_keywords     jsonb       not null default '[]'::jsonb,
  meta_description text,

  active           boolean     not null default true,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists products_active_idx   on public.products (active) where deleted_at is null;
create index if not exists products_category_idx on public.products (category);
-- The catalogue is served on every page load; this is the query it makes.
create index if not exists products_listing_idx  on public.products (active, category) where deleted_at is null;
-- Named as a survivor by 014_drop_duplicate_indexes.sql.
create index if not exists products_deleted_idx  on public.products (deleted_at) where deleted_at is not null;

-- ─────────────────────────────────────────────────────────────────────
-- CUSTOMERS
--   email is the identity the whole application joins on. 007 normalises
--   case; the unique index here is on lower(email) so two spellings of
--   one address can never both exist. `password` is a bcrypt hash and is
--   null for accounts created by Google sign-in or by checkout.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.customers (
  id           bigint generated by default as identity primary key,
  name         text        not null default '',
  email        text        not null,
  phone        text,
  password     text,

  city         text,
  state        text,
  pincode      text,
  address      text,

  total_orders integer       not null default 0,
  total_spent  numeric(12,2) not null default 0,

  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create unique index if not exists customers_email_lower_key on public.customers (lower(email));

-- ─────────────────────────────────────────────────────────────────────
-- ORDERS
--   id is text, not a sequence: order numbers are human-facing strings
--   minted by the storefront/gateway (ORD-…, the GoKwik merchant ref,
--   the Cashfree order id) and are the idempotency key every payment
--   confirmation path checks before inserting. A serial would let the
--   same payment create two orders.
--
--   Column set is exactly the ORDER_COLUMNS whitelist in sp_place_order.
--   Anything not listed there is dropped before the insert, so a column
--   missing here silently loses data — keep the two in step.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.orders (
  id               text primary key,
  user_id          bigint references public.customers(id) on delete set null,

  customer_name    text,
  customer_email   text,
  customer_phone   text,
  address          text,
  city             text,
  state            text,
  pincode          text,
  country          text default 'India',

  items            jsonb       not null default '[]'::jsonb,

  -- Money. Recomputed server-side by computeServerSideTotal() on every
  -- path; the client's numbers are never trusted.
  subtotal         numeric(10,2) not null default 0,
  discount         numeric(10,2) not null default 0,
  shipping         numeric(10,2) not null default 0,
  total            numeric(10,2) not null default 0,

  -- Per-component discount breakdown, written by persistBreakdown() in
  -- order-breakdown.js so the invoice and My Account can name each
  -- discount rather than showing one merged figure. (020)
  tier_discount        numeric(10,2) not null default 0,
  mix_match_discount   numeric(10,2) not null default 0,
  coupon_discount      numeric(10,2) not null default 0,
  vita_points_discount numeric(10,2) not null default 0,
  vita_points_used     integer       not null default 0,

  coupon_code      text,
  vita_points_redeemed integer not null default 0,
  vita_points_earned   integer not null default 0,

  payment_method   text,
  payment_status   text        not null default 'Pending',
  payment_gateway  text,
  cf_order_id      text,
  cf_payment_id    text,
  cashfree_order_id text,

  status           text,
  fulfillment      text        not null default 'Pending',
  shiprocket_id    text,
  delhivery_waybill text,
  courier          text,
  tracking_url     text,
  delivered_at     timestamptz,

  notes            text,
  client_ip        text,
  device_fp        text,

  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists orders_email_idx    on public.orders (lower(customer_email));
create index if not exists orders_created_idx  on public.orders (created_at desc);
create index if not exists orders_fulfil_idx   on public.orders (fulfillment);
create index if not exists orders_payment_idx  on public.orders (payment_status);
create index if not exists orders_waybill_idx  on public.orders (delhivery_waybill) where delhivery_waybill is not null;
-- "My orders" is the hottest customer query: newest-first for one email.
create index if not exists orders_email_created_idx on public.orders (lower(customer_email), created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- ORDER STATUS LOGS — the fulfilment audit trail behind order tracking
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.order_status_logs (
  id          bigint generated by default as identity primary key,
  order_id    text not null references public.orders(id) on delete cascade,
  old_status  text,
  new_status  text,
  changed_by  text,
  note        text,
  created_at  timestamptz not null default now()
);
create index if not exists order_status_logs_order_idx on public.order_status_logs (order_id, created_at);

-- ─────────────────────────────────────────────────────────────────────
-- COUPONS
--   Shape is buildCouponPayload() exactly. used_count is advanced only by
--   claim_coupon_use() (006) — an atomic guarded increment. Never write
--   it with a read-then-write: concurrent checkouts on a single-use code
--   is the exact race that function exists to close.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.coupons (
  id                    bigint generated by default as identity primary key,
  code                  text not null,
  type                  text not null check (type in ('percent','flat')),
  value                 numeric(10,2) not null check (value > 0),
  min_order             numeric(10,2),
  max_discount          numeric(10,2),
  max_uses              integer check (max_uses is null or max_uses >= 1),
  max_uses_per_customer integer check (max_uses_per_customer is null or max_uses_per_customer >= 1),
  used_count            integer not null default 0,
  description           text,
  expires_at            timestamptz,
  active                boolean not null default true,
  deleted_at            timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- Codes are upper-cased before every read and write, so uniqueness is on
-- the upper-cased value. The insert path relies on 23505 from this index
-- to report "a coupon with this code already exists".
create unique index if not exists coupons_code_key on public.coupons (upper(code));
create index if not exists coupons_active_idx on public.coupons (active) where deleted_at is null;

-- ─────────────────────────────────────────────────────────────────────
-- REFUNDS
--   gateway_refund_id is the provider's own id. It is the idempotency
--   key for a refund webhook: unique-when-present, so a redelivered
--   refund event cannot create a second row.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.refunds (
  id                bigint generated by default as identity primary key,
  order_id          text not null references public.orders(id) on delete cascade,
  return_id         uuid,
  gateway           text not null default 'manual',
  gateway_refund_id text,
  amount            numeric(10,2) not null,
  status            text not null default 'processed'
                    check (status in ('pending','processed','failed','cancelled')),
  note              text,
  raw_response      jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists refunds_order_idx on public.refunds (order_id);
create unique index if not exists refunds_gateway_ref_key
  on public.refunds (gateway, gateway_refund_id)
  where gateway_refund_id is not null;

-- ─────────────────────────────────────────────────────────────────────
-- REVIEWS
--   One review per customer per product — enforced here, not only in the
--   route, so a double-submit races into a 23505 instead of two rows.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.reviews (
  id             bigint generated by default as identity primary key,
  product_id     bigint references public.products(id) on delete cascade,
  product_name   text,
  user_name      text not null default 'Customer',
  customer_email text not null,
  rating         integer not null check (rating between 1 and 5),
  review_text    text,
  verified       boolean not null default false,
  status         text    not null default 'approved'
                 check (status in ('pending','approved','rejected')),
  admin_reply    text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create unique index if not exists reviews_one_per_product_key
  on public.reviews (product_id, lower(customer_email));
-- Named to match the survivor 014_drop_duplicate_indexes.sql expects.
-- Under the old name (reviews_product_idx) that migration would drop this,
-- and the index it names as the survivor does not exist on a fresh
-- database — leaving reviews with no index on product_id at all.
create index if not exists reviews_product_id_idx on public.reviews (product_id, status);
create index if not exists reviews_status_idx  on public.reviews (status, created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- SETTINGS — key/value store for runtime configuration the admin edits
--   (discount ceilings, 2fa_master_enabled, …). Values are text and
--   parsed at the call site.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.settings (
  key        text primary key,
  value      text,
  updated_by text,
  updated_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────
-- AUDIT LOGS — written by writeAudit() on every privileged mutation
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.audit_logs (
  id         bigint generated by default as identity primary key,
  user_id    text,
  table_name text,
  record_id  text,
  action     text,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_table_idx   on public.audit_logs (table_name, created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- SYSTEM ALERTS — operational alerts surfaced in the admin panel
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.system_alerts (
  id          bigint generated by default as identity primary key,
  severity    text not null default 'warn' check (severity in ('info','warn','critical')),
  category    text,
  title       text not null,
  detail      text,
  order_id    text,
  resolved_at timestamptz,
  resolved_by text,
  created_at  timestamptz not null default now()
);
create index if not exists system_alerts_open_idx on public.system_alerts (created_at desc) where resolved_at is null;

-- ─────────────────────────────────────────────────────────────────────
-- FRAUD VELOCITY — rolling event counter behind checkVelocity()
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.fraud_velocity (
  id          bigint generated by default as identity primary key,
  scope       text not null,          -- 'email' | 'ip'
  scope_value text not null,
  event       text not null,
  created_at  timestamptz not null default now()
);
create index if not exists fraud_velocity_lookup_idx
  on public.fraud_velocity (scope, scope_value, created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- ADMIN TOKEN VERSIONS
--   Bumping `version` instantly invalidates every outstanding JWT for
--   that identity. Without it, rotating an admin password did not revoke
--   tokens already issued.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.auth_token_versions (
  identity   text primary key,
  version    integer not null default 1,
  updated_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────
-- SITE / PROMO MEDIA
--   The asset-indirection layer: the storefront resolves banners, hero
--   art and category images through these keys rather than hard-coded
--   paths, so artwork is replaced from the admin panel without a deploy.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.site_media (
  key        text primary key,
  url        text not null,
  alt        text,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_media (
  id         bigint generated by default as identity primary key,
  url        text not null,
  poster     text,
  title      text,
  subtitle   text,
  link       text,
  media_type text not null default 'image',
  sort_order integer not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists promo_media_order_idx on public.promo_media (active, sort_order);

-- ─────────────────────────────────────────────────────────────────────
-- STORE CONTENTS — editable storefront copy (hero, announcements, trust
--   tiles) published from the admin panel. One row per store key.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.store_contents (
  store_key  text primary key,
  contents   jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────
-- VISITOR ANALYTICS
--   ip_hash only — the raw IP is never stored. session_id is client-
--   minted, so it is the natural key and must be unique or a re-ping
--   would fork the session.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.visitor_sessions (
  session_id   text primary key,
  site         text,
  ip_hash      text,
  country      text,
  city         text,
  device_type  text,
  os           text,
  os_version   text,
  browser      text,
  screen_w     integer,
  screen_h     integer,
  is_pwa       boolean not null default false,
  is_bot       boolean not null default false,
  referrer     text,
  source       text,
  utm_source   text,
  utm_medium   text,
  utm_campaign text,
  landing_page text,
  last_page    text,
  page_views   integer not null default 1,
  duration_sec integer not null default 0,
  converted    boolean not null default false,
  order_id     text,
  user_email   text,
  first_seen   timestamptz not null default now(),
  last_seen    timestamptz not null default now()
);
create index if not exists visitor_sessions_live_idx on public.visitor_sessions (last_seen desc) where is_bot = false;
create index if not exists visitor_sessions_site_idx on public.visitor_sessions (site, last_seen desc);

create table if not exists public.visitor_pageviews (
  id          bigint generated by default as identity primary key,
  session_id  text,
  page        text,
  device_type text,
  os          text,
  source      text,
  at          timestamptz not null default now()
);
create index if not exists visitor_pageviews_at_idx on public.visitor_pageviews (at desc);

-- ─────────────────────────────────────────────────────────────────────
-- AI ACTIONS — owner-approved agent action queue
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.ai_actions (
  id           bigint generated by default as identity primary key,
  agent_id     text,
  agent_name   text,
  action_type  text,
  summary      text,
  payload      jsonb not null default '{}'::jsonb,
  status       text  not null default 'pending'
               check (status in ('pending','approved','rejected','executed','failed')),
  approved_by  text,
  approved_at  timestamptz,
  result       jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists ai_actions_status_idx on public.ai_actions (status, created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- WEBHOOK EVENTS
--   NEW IN THIS FORK. The system this was taken from had no webhook
--   event log: each handler open-coded its own idempotency by looking
--   for an existing order row. That covers a redelivered *payment*
--   webhook, but nothing else — a repeated shipping or refund event had
--   no record that it had already been processed.
--
--   Handlers record (provider, event_id) here before acting. The unique
--   index is the idempotency guard: a duplicate delivery loses the race
--   on insert (23505) and is acknowledged without re-running the effect.
-- ─────────────────────────────────────────────────────────────────────
create table if not exists public.webhook_events (
  id           bigint generated by default as identity primary key,
  provider     text not null,             -- 'cashfree' | 'gokwik' | 'delhivery'
  event_id     text not null,             -- the provider's own event/delivery id
  event_type   text,
  order_id     text,
  signature_ok boolean not null default false,
  payload      jsonb,
  processed_at timestamptz,
  error        text,
  received_at  timestamptz not null default now()
);
create unique index if not exists webhook_events_dedupe_key
  on public.webhook_events (provider, event_id);
create index if not exists webhook_events_order_idx on public.webhook_events (order_id, received_at desc);

-- ═════════════════════════════════════════════════════════════════════
-- BASE-SCHEMA FUNCTIONS
--
--   Migration 011 is an ALTER-only file generated from a live inventory
--   of the production database, and 015 names the trigger functions
--   explicitly. Between them they prove nine functions existed in that
--   database that NO migration in this directory creates — they were
--   made by hand in the dashboard and were never captured anywhere:
--
--     fn_set_updated_at        fn_prevent_negative_stock
--     fn_update_customer_stats fn_auto_log_order_status
--     fn_auto_coupon_usage     fn_sync_order_status
--     vita_ledger_immutable    get_dashboard_kpis
--     purge_soft_deletes       validate_coupon
--
--   Applying 011 or 015 without them fails. They are reconstructed below
--   from their names, from 015's description of how each is invoked, and
--   from the behaviour the application depends on.
--
--   ⚠️ WHICH TRIGGERS ARE ATTACHED, AND WHY NOT ALL OF THEM
--     Three of these functions duplicate work the Node server already
--     does on every write path:
--       • fn_update_customer_stats  — server.js increments
--         customers.total_orders / total_spent itself after each order.
--       • fn_auto_coupon_usage      — coupon uses are claimed atomically
--         through claim_coupon_use() before the order row is written.
--       • fn_auto_log_order_status  — the server inserts its own
--         order_status_logs row, with the acting user in changed_by.
--     Attaching those as triggers on a database whose application also
--     performs the write means every order counts twice, every coupon
--     burns two uses, and the status history doubles. The functions are
--     therefore CREATED (so 011/015 apply, and so the objects match the
--     inventory) but deliberately NOT attached. Attach one only if the
--     corresponding application-side write is removed first.
--
--     The three that ARE attached — fn_set_updated_at,
--     fn_prevent_negative_stock, vita_ledger_immutable — are guards, not
--     counters. They are idempotent and cannot double-count.
-- ═════════════════════════════════════════════════════════════════════

-- ── Attached. Guarantees updated_at even on paths that forget it. ─────
create or replace function public.fn_set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'products','customers','orders','coupons','refunds','reviews',
    'settings','site_media','promo_media','store_contents',
    'ai_actions','auth_token_versions'
  ] loop
    execute format('drop trigger if exists %I on public.%I', 'trg_touch_' || t, t);
    execute format(
      'create trigger %I before update on public.%I
         for each row execute function public.fn_set_updated_at()',
      'trg_touch_' || t, t);
  end loop;
end $$;


-- ── Attached. Stock must never go below zero. ────────────────────────
-- decrement_stock_strict (002) already refuses to oversell, but direct
-- admin edits and the fallback path in sp_place_order both write stock
-- without it. This is the backstop that makes negative stock impossible
-- however the row is reached.
create or replace function public.fn_prevent_negative_stock()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.stock is null then new.stock := 0; end if;
  if new.stock < 0 then
    raise exception 'Stock cannot be negative (product %, attempted %)', new.id, new.stock
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_negative_stock on public.products;
create trigger trg_prevent_negative_stock
  before insert or update of stock on public.products
  for each row execute function public.fn_prevent_negative_stock();


-- ── NOT attached (see the warning above): duplicates server.js. ──────
-- Recomputes a customer's order count and lifetime spend from the orders
-- table. Written as a full recompute rather than a delta so that if it
-- IS ever attached it is self-correcting and cannot drift.
create or replace function public.fn_update_customer_stats()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_email text := lower(coalesce(new.customer_email, old.customer_email, ''));
begin
  if v_email = '' then return coalesce(new, old); end if;
  update public.customers c
     set total_orders = sub.n, total_spent = sub.sum_total
    from (
      select count(*) as n, coalesce(sum(o.total), 0) as sum_total
        from public.orders o
       where lower(o.customer_email) = v_email
         and o.deleted_at is null
    ) sub
   where lower(c.email) = v_email;
  return coalesce(new, old);
end;
$$;

-- ── NOT attached: coupon uses are claimed by claim_coupon_use(). ─────
create or replace function public.fn_auto_coupon_usage()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.coupon_code is not null and btrim(new.coupon_code) <> '' then
    update public.coupons
       set used_count = coalesce(used_count, 0) + 1
     where upper(code) = upper(btrim(new.coupon_code));
  end if;
  return new;
end;
$$;

-- ── NOT attached: server.js writes its own row, with a real actor. ───
create or replace function public.fn_auto_log_order_status()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'UPDATE' and new.fulfillment is distinct from old.fulfillment then
    insert into public.order_status_logs (order_id, old_status, new_status, changed_by)
    values (new.id, old.fulfillment, new.fulfillment, 'db-trigger');
  end if;
  return new;
end;
$$;

-- ── NOT attached: keeps the legacy `status` column in step with
--    `fulfillment`. The application reads `fulfillment`; `status` is a
--    older duplicate kept for compatibility with saved admin views.
create or replace function public.fn_sync_order_status()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.status := new.fulfillment;
  return new;
end;
$$;


-- ── Admin dashboard KPI aggregate. ──────────────────────────────────
-- One round trip instead of six. Returns a single jsonb object; the
-- admin panel reads the keys it needs.
create or replace function public.get_dashboard_kpis()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'orders_total',    (select count(*) from public.orders where deleted_at is null),
    'orders_today',    (select count(*) from public.orders
                         where deleted_at is null and created_at >= date_trunc('day', now())),
    'revenue_total',   (select coalesce(sum(total), 0) from public.orders
                         where deleted_at is null and payment_status ilike '%paid%'),
    'revenue_today',   (select coalesce(sum(total), 0) from public.orders
                         where deleted_at is null and payment_status ilike '%paid%'
                           and created_at >= date_trunc('day', now())),
    'customers_total', (select count(*) from public.customers where deleted_at is null),
    'pending_orders',  (select count(*) from public.orders
                         where deleted_at is null and fulfillment = 'Pending'),
    'low_stock',       (select count(*) from public.products
                         where deleted_at is null and active and stock <= 5),
    'open_alerts',     (select count(*) from public.system_alerts where resolved_at is null),
    'pending_reviews', (select count(*) from public.reviews where status = 'pending')
  );
$$;


-- ── Hard-delete rows that have been soft-deleted for long enough. ────
-- Retention is a deliberate, operator-invoked action: this is called by
-- the scheduled purge, never by a request path.
create or replace function public.purge_soft_deletes(p_days_old integer default 90)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  cutoff timestamptz := now() - make_interval(days => greatest(p_days_old, 1));
  n_products int; n_customers int; n_orders int; n_coupons int;
begin
  delete from public.products  where deleted_at is not null and deleted_at < cutoff;
  get diagnostics n_products = row_count;
  delete from public.coupons   where deleted_at is not null and deleted_at < cutoff;
  get diagnostics n_coupons = row_count;
  -- Orders are financial records: a soft-deleted order still anchors
  -- refunds, returns and the loyalty ledger, so it is held far longer
  -- than the generic window and never less than seven years.
  delete from public.orders    where deleted_at is not null
                                 and deleted_at < now() - interval '7 years';
  get diagnostics n_orders = row_count;
  delete from public.customers where deleted_at is not null and deleted_at < cutoff
                                 and not exists (
                                   select 1 from public.orders o
                                    where lower(o.customer_email) = lower(customers.email));
  get diagnostics n_customers = row_count;

  return jsonb_build_object('products', n_products, 'coupons', n_coupons,
                            'orders', n_orders, 'customers', n_customers,
                            'cutoff', cutoff);
end;
$$;


-- ── Read-only coupon check. ─────────────────────────────────────────
-- The authoritative claim is claim_coupon_use() (006), which is atomic
-- and mutates. This one only reports whether a code *would* apply, for
-- the storefront's live "apply coupon" feedback.
create or replace function public.validate_coupon(p_code text, p_order_value numeric)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare c public.coupons%rowtype; v_discount numeric;
begin
  select * into c from public.coupons
   where upper(code) = upper(btrim(p_code)) and deleted_at is null;

  if not found                                    then return jsonb_build_object('valid', false, 'reason', 'Coupon not found'); end if;
  if not c.active                                 then return jsonb_build_object('valid', false, 'reason', 'Coupon is not active'); end if;
  if c.expires_at is not null and c.expires_at < now()
                                                  then return jsonb_build_object('valid', false, 'reason', 'Coupon has expired'); end if;
  if c.max_uses is not null and coalesce(c.used_count, 0) >= c.max_uses
                                                  then return jsonb_build_object('valid', false, 'reason', 'Coupon usage limit reached'); end if;
  if c.min_order is not null and p_order_value < c.min_order
                                                  then return jsonb_build_object('valid', false, 'reason',
                                                         format('Minimum order value is %s', c.min_order)); end if;

  v_discount := case when c.type = 'percent'
                     then round(p_order_value * c.value / 100.0, 2)
                     else c.value end;
  if c.max_discount is not null then v_discount := least(v_discount, c.max_discount); end if;
  v_discount := least(v_discount, p_order_value);

  return jsonb_build_object('valid', true, 'discount', v_discount,
                            'type', c.type, 'value', c.value, 'code', c.code);
end;
$$;


-- ── Attached (in 001, to vita_ledger). Makes the loyalty ledger
--    append-only: a balance derived from an immutable ledger cannot be
--    silently rewritten. Defined here because 011 and 015 both name it
--    and no migration ever created it.
create or replace function public.vita_ledger_immutable()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  raise exception 'vita_ledger is append-only — % is not permitted', tg_op
    using errcode = 'insufficient_privilege';
end;
$$;

-- ─────────────────────────────────────────────────────────────────────
-- Verification — prints what is now present.
-- ─────────────────────────────────────────────────────────────────────
do $$
declare missing text[] := '{}';
        t text;
begin
  foreach t in array array[
    'products','customers','orders','order_status_logs','coupons','refunds',
    'reviews','settings','audit_logs','system_alerts','fraud_velocity',
    'auth_token_versions','site_media','promo_media','store_contents',
    'visitor_sessions','visitor_pageviews','ai_actions','webhook_events'
  ] loop
    if to_regclass('public.' || t) is null then missing := missing || t; end if;
  end loop;

  if array_length(missing, 1) is null then
    raise notice 'BASE SCHEMA OK — all 19 tables present. Next: 002_atomic_counters.sql';
  else
    raise warning 'BASE SCHEMA INCOMPLETE — missing: %', array_to_string(missing, ', ');
  end if;
end $$;
